### ISSUE TITLE
Missing value for Stripe(): apiKey should be a string.

### ISSUE THREAD

**Issue by HamzaAhmedSheikh** [usmanashrf/Nextjs13_Stripe_Integration#1]
I encountered that problem in this application.
![screenshot](https://github.com/usmanashrf/Nextjs13_Stripe_Integration/assets/52938118/cc9cb656-6f7b-45a3-b7d6-6603b21981a4)

**Comment by usmanashrf** [comment]
You are getting this because you haven't set your local variables in .env.local file, so please make sure you added below variables with value in your .env.local file. 

- NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
- STRIPE_SECRET_KEY

You'll get the value of these variable from stripe dashboard
